name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  create-tag:
    name: Create tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check output
        env:
          RELEASE_VERSION: ${GITHUB_REF#refs/*/}
        run: |
          echo $RELEASE_VERSION

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
        - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
        
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/*/}

      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.tag_version.outputs.VERSION }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

  # release-binaries:
  #     name: release linux/amd64
  #     runs-on: ubuntu-latest
  #     strategy:
  #       matrix:
  #         goos: [linux, darwin]
  #         goarch: ["386", amd64]
  #         exclude:
  #           - goarch: "386"
  #             goos: darwin
  #     steps:        
  #     - uses: actions/checkout@v2
  #     - name: Get the version
  #       id: get_version
  #       run: echo ::set-output name=VERSION::${GITHUB_REF#refs/*/}
  #     - uses: wangyoucao577/go-release-action@v1.16
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         goos: ${{ matrix.goos }}
  #         goarch: ${{ matrix.goarch }}
  #         build_flags: -v
  #         ldflags: -X "cmd.appVersion=${{ steps.get_version.outputs.VERSION }}"
  #         asset_name: covid-vaccine-tracker_${{ steps.get_version.outputs.VERSION }}_${{ matrix.goos }}_${{ matrix.goarch }}
      # - name: Update release with zip
      #   uses: johnwbyrd/update-release@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     asset: ./the-file-you-want-to-release.zip