name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  create-release:
    #needs: [create-tag]
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      - uses: actions/setup-go@v1
        with:
          go-version: '1.16' # The Go version to download (if necessary) and use.
      - run: |
          go version
          env GOOS=linux go build -ldflags="-s -w" -o bin/covid-vaccine-notifier main.go
          zip covid-vaccine-notifier.zip bin/covid-vaccine-notifier
     - name: Update release with zip
        uses: johnwbyrd/update-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          asset: ./covid-vaccine-notifier.zip

  # release-binaries:
  #     name: release linux/amd64
  #     runs-on: ubuntu-latest
  #     strategy:
  #       matrix:
  #         goos: [linux, darwin]
  #         goarch: ["386", amd64]
  #         exclude:
  #           - goarch: "386"
  #             goos: darwin
  #     steps:        
  #     - uses: actions/checkout@v2
  #     - name: Get the version
  #       id: get_version
  #       run: echo ::set-output name=VERSION::${GITHUB_REF#refs/*/}
  #     - uses: wangyoucao577/go-release-action@v1.16
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         goos: ${{ matrix.goos }}
  #         goarch: ${{ matrix.goarch }}
  #         build_flags: -v
  #         ldflags: -X "cmd.appVersion=${{ steps.get_version.outputs.VERSION }}"
  #         asset_name: covid-vaccine-tracker_${{ steps.get_version.outputs.VERSION }}_${{ matrix.goos }}_${{ matrix.goarch }}
      # - name: Update release with zip
      #   uses: johnwbyrd/update-release@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     asset: ./the-file-you-want-to-release.zip